# Generated by Django 2.2.7 on 2019-11-26 09:35

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('todoapp', '0003_auto_20191126_0934'),
    ]

    operations = [
        migrations.AlterModelTable(
            name='todo',
            table=None,
        ),
    ]
