# Generated by Django 2.2.7 on 2019-11-26 09:34

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('todoapp', '0002_auto_20191126_0933'),
    ]

    operations = [
        migrations.AlterModelTable(
            name='todo',
            table='todo',
        ),
    ]
